// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-c7cComsCA86SduSnDT1e7WxMw_FuSZk',
    appId: '1:53771576792:web:907cc3aea362074fea3ead',
    messagingSenderId: '53771576792',
    projectId: 'finalprojectflutter-a655c',
    authDomain: 'finalprojectflutter-a655c.firebaseapp.com',
    storageBucket: 'finalprojectflutter-a655c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClf5gWd9YwFTKp6dpwlm59HbCa9cWrNaU',
    appId: '1:53771576792:android:c18a4193acf8a083ea3ead',
    messagingSenderId: '53771576792',
    projectId: 'finalprojectflutter-a655c',
    storageBucket: 'finalprojectflutter-a655c.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-c7cComsCA86SduSnDT1e7WxMw_FuSZk',
    appId: '1:53771576792:web:31e2112fa52e499dea3ead',
    messagingSenderId: '53771576792',
    projectId: 'finalprojectflutter-a655c',
    authDomain: 'finalprojectflutter-a655c.firebaseapp.com',
    storageBucket: 'finalprojectflutter-a655c.appspot.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyB-c7cComsCA86SduSnDT1e7WxMw_FuSZk',
    appId: '1:53771576792:web:80e7d427a998e5ffea3ead',
    messagingSenderId: '53771576792',
    projectId: 'finalprojectflutter-a655c',
    authDomain: 'finalprojectflutter-a655c.firebaseapp.com',
    storageBucket: 'finalprojectflutter-a655c.appspot.com',
  );
}
